# Generated by Django 4.2.7 on 2023-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=100)),
                ('monthly_salary', models.CharField(max_length=10000)),
            ],
        ),
    ]
